[package]
name = "elk-mq"
version = "0.1.0"
edition = "2021"
authors = [
    "Tijmen Verhoef<tijmenmenno@gmail.com>"
]

[lib]
crate-type = [ "lib", "staticlib", "cdylib" ]

[features]
python_bindings = [ "cpython" ]

[dependencies]
redis = { version="0.22" }
serde = { version="1.0", features=[ "derive" ] }
serde_json = { version="1.0" }
uuid = { version="1.2", features=[ "v4" ] }
regex = { version="1.7" }
lazy_static = { version="1.4" }
cpython = { version="0.7", features=["extension-module"], optional=true }
