[package]
name = "common-service-interface"
version = "0.1.0"
edition = "2021"
authors = [
    "Tijmen Verhoef<tijmenmenno@gmail.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version="0.22" }
serde = { version="1.0", features=[ "derive" ] }
serde_json = { version="1.0" }
uuid = { version="1.2", features=[ "v4" ] }
regex = { version="1.7" }
lazy_static = { version="1.4" }
